/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iorganizer;

import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class buttonLogic extends javax.swing.JFrame {
  mainFrame mf;
  String button;
  File f;
  String path,imageAddress;
  String itemList,add;
  File f2;
  Image i;
    /**
     * Creates new form Mythology
     */
  void labelPasteAction()
  {
      
  }
  void clickAction()
  {
       path ="C:\\Users\\user\\Desktop" +"\\"+button;
         
         f=new File(path);
        if(!f.exists())
        {
            f.mkdir();
        }
        String contents[] = f.list();
      DisplayDirectoryContents(contents);
     
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
  }
  void DisplayDirectoryContents(String s[])
  {
      for(int i=0;i<s.length;i++)
      {
          int j= s[i].lastIndexOf('.');
          String newname= s[i].substring(0,j);
          df.addElement(newname);
      }
  }

  String getAdd()
     {
      return add;   
     }
    class value implements ActionListener{
     JDialog d;
     JButton jb;
     JTextField jf;
     
     
    value ()
    {
        d= new JDialog();
        d.setLayout(new FlowLayout());
        
         jb= new JButton("OK");
         jf= new JTextField(20);
        jb.addActionListener(this);
        d.setSize(300,300);
        d.add(jf);
        d.add(jb);
        d.setVisible(true);
     }
    String newValue()
    {
        
        return jf.getText();
    }
    
    public void actionPerformed(ActionEvent ae)
    {
         itemList= newValue();
         
        df.addElement(itemList);
        d.dispose();
    }
    String getItemvalue()
    {
        return itemList;
    }
    
} 
   
    public buttonLogic() {
       
        initComponents();
      
        setSize(400,300);
        setResizable(false);
         
        
    }
   void setpath(String path)
   {
       this.path= path;
   }
   void setimageAddress(String imageAddress)
   {
       this.imageAddress= imageAddress;
   }
   void setButtonName(String button)
   {
     this.button = button;
   }

 DefaultListModel<String> df = new DefaultListModel<String>();
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>(df);
        jPanel2 = new javax.swing.JPanel();
        subCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText(" Choose a sub category");
        getContentPane().add(jLabel1);

        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        subCategory.setText("Enter a sub-category ");
        subCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subCategory)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(subCategory)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCategoryActionPerformed
        value v = new value();
       
        
    }//GEN-LAST:event_subCategoryActionPerformed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
       try{
            add= (String) list.getSelectedValue();
           
        String filePath = path+"\\"+add+".txt";
        f2= new File(filePath);
         FileWriter fo  = new FileWriter(filePath,true);
        BufferedWriter bf1 = new BufferedWriter(fo);
         
         if(f2.exists())
         {
          bf1.write(imageAddress);
          bf1.newLine();
         }
         else
         {
             f2.createNewFile();
         }
         bf1.close();
         
       }
       catch (FileNotFoundException f)
       {
           System.out.println("File not found");
       } catch (IOException ex) {
          System.out.println("Couldn't paste file");
      }
       
       
    }//GEN-LAST:event_listMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buttonLogic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buttonLogic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buttonLogic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buttonLogic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new buttonLogic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JButton subCategory;
    // End of variables declaration//GEN-END:variables
}
