/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iorganizer;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import static java.util.Locale.filter;
import java.util.Scanner;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.TransferHandler;
import javax.swing.border.Border;

/**
 *
 * @author user
 */

public class mainFrame extends javax.swing.JFrame {
 
     Image i=null,img=null;
     String imageAddress=null;
     
     String path;
      
     JLabel label ;
     
  
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel3 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Religious = new javax.swing.JButton();
        Celebrities = new javax.swing.JButton();
        Funny = new javax.swing.JButton();
        Electronics = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Open = new javax.swing.JButton();
        Thumbnail = new javax.swing.JButton();
        New = new javax.swing.JButton();
        scrollpane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.FlowLayout());

        l2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        l2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l2MouseDragged(evt);
            }
        });
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        Religious.setText("Religious");
        Religious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReligiousMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ReligiousMouseReleased(evt);
            }
        });
        Religious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReligiousActionPerformed(evt);
            }
        });
        jPanel1.add(Religious);

        Celebrities.setText("Celebrities");
        Celebrities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelebritiesActionPerformed(evt);
            }
        });
        jPanel1.add(Celebrities);

        Funny.setText("Funny");
        Funny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunnyActionPerformed(evt);
            }
        });
        jPanel1.add(Funny);

        Electronics.setText("Electronics");
        Electronics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElectronicsActionPerformed(evt);
            }
        });
        jPanel1.add(Electronics);

        Open.setText("open");
        Open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OpenMouseEntered(evt);
            }
        });
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        Thumbnail.setText("Create Thumbnail");
        Thumbnail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThumbnailActionPerformed(evt);
            }
        });

        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(Thumbnail)
                .addGap(82, 82, 82)
                .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Open)
                .addComponent(Thumbnail)
                .addComponent(New))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollpane))))
                .addGap(0, 220, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        // TODO add your handling code here:
      Operations im= new Operations();
        
        try 
        {
             Clipboard clip= getToolkit().getSystemClipboard();
            Transferable pasteText = clip.getContents(mainFrame.this);
        imageAddress = (String) pasteText.getTransferData(DataFlavor.stringFlavor);
        }
      catch (Exception E){
            JOptionPane.showMessageDialog(rootPane, E, "Paste not possible", HEIGHT);
          }
        try{
            
            i=im.search(imageAddress);
            i= i.getScaledInstance(l2.getWidth(), l2.getHeight(),WIDTH);
           l2.setIcon(new ImageIcon(i));
         }
        catch (IOException ex)
                {
                l2.setIcon(null);
              l2.setText("Load not possible");
              System.out.println("The given address is either too long or it is not an address of an image");
                }
       
    }//GEN-LAST:event_l2MouseClicked

    private void l2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseDragged
    
       
        
    }//GEN-LAST:event_l2MouseDragged

    private void ReligiousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReligiousActionPerformed
        buttonLogic m = new buttonLogic();
        path = Religious.getActionCommand(); 
        m.setButtonName(path);
        m.setpath(path);
        m.setimageAddress(imageAddress);
        m.clickAction();
        
    }//GEN-LAST:event_ReligiousActionPerformed

    private void ReligiousMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReligiousMouseReleased
        
      
    }//GEN-LAST:event_ReligiousMouseReleased

    private void ReligiousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReligiousMouseEntered
        Religious.setToolTipText(Religious.getText());
    }//GEN-LAST:event_ReligiousMouseEntered

    private void OpenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMouseEntered
        Open.setToolTipText("Open a saved link");
    }//GEN-LAST:event_OpenMouseEntered

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
JFileChooser fileChooser = new JFileChooser();
fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
int result = fileChooser.showOpenDialog(this);
try{
    

if (result == JFileChooser.APPROVE_OPTION) {
    File selectedFile = fileChooser.getSelectedFile();
    System.out.println("Selected file: " + selectedFile.getAbsolutePath());
    Desktop.getDesktop().open(selectedFile);
}        // TODO add your handling code here:
}    

 catch (IOException e)
 {
     System.out.println("Could not open the file");
 }     
    }//GEN-LAST:event_OpenActionPerformed

    private void CelebritiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelebritiesActionPerformed
        buttonLogic c = new buttonLogic();
        path = Celebrities.getActionCommand(); 
        c.setButtonName(path);
        c.setpath(path);
        c.setimageAddress(imageAddress);
        c.clickAction();
    }//GEN-LAST:event_CelebritiesActionPerformed

    private void FunnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunnyActionPerformed
       buttonLogic fu = new buttonLogic();
        path = Funny.getActionCommand(); 
        fu.setButtonName(path);
        fu.setpath(path);
        fu.setimageAddress(imageAddress);
        fu.clickAction();
    }//GEN-LAST:event_FunnyActionPerformed

    private void ElectronicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElectronicsActionPerformed
        buttonLogic e = new buttonLogic();
        path =Electronics.getActionCommand(); 
        e.setButtonName(path);
        e.setpath(path);
        e.setimageAddress(imageAddress);
        e.clickAction();
    }//GEN-LAST:event_ElectronicsActionPerformed

    private void ThumbnailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThumbnailActionPerformed
    
      img =i.getScaledInstance(scrollpane.getHeight(), 100, Image.SCALE_SMOOTH);
      label = new JLabel();
      Border border = BorderFactory.createLineBorder(Color.black);
      label.setBorder(border);
      label.setSize(scrollpane.getHeight(),100);
      label.setIcon(new ImageIcon(img));
      scrollpane.add(label);
      scrollpane.validate();
    }//GEN-LAST:event_ThumbnailActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        jPanel1.add(new JButton());
        jPanel1.validate();
    }//GEN-LAST:event_NewActionPerformed
 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Celebrities;
    private javax.swing.JButton Electronics;
    private javax.swing.JButton Funny;
    private javax.swing.JButton New;
    private javax.swing.JButton Open;
    javax.swing.JButton Religious;
    private javax.swing.JButton Thumbnail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    javax.swing.JLabel l2;
    private javax.swing.JScrollPane scrollpane;
    // End of variables declaration//GEN-END:variables
}
